version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb_service
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  scraper:
    build: ./scraper
    container_name: waze_scraper
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/traffic_data
      STORAGE_SERVICE_URL: http://storage:5001/event # Si tu scraper usa el servicio storage
    depends_on:
      mongodb:
        condition: service_healthy
      storage: # Si el scraper envía datos al servicio storage, depende de él
        condition: service_started
    networks:
      - my_network

  storage:
    build: ./storage
    container_name: waze_storage_service
    ports:
      - "5001:5001"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/traffic_data
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - my_network
    healthcheck: # Si tienes un endpoint /health en tu servicio Flask
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  hadoop-pig-master:
    build:
      context: .
      dockerfile: Dockerfile.hadoop-pig
    container_name: hadoop_pig_master
    environment:
      HADOOP_CONF_DIR: /usr/local/hadoop/etc/hadoop
    ports:
      - "8088:8088"
      - "9870:9870"
      - "50070:50070"
    depends_on:
      mongodb:
        condition: service_healthy # Pig lee de MongoDB
      # No depende de scraper/storage directamente para iniciar, pero sí para tener datos
    volumes:
      - ./filtering:/opt/pig_scripts/filtering # Monta el directorio de scripts de Filtering
      - ./processing:/opt/pig_scripts/processing # Monta el directorio de scripts de Processing
    networks:
      - my_network

volumes:
  mongodb_data:

networks:
  my_network:
    driver: bridge