version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./storage/init.js:/docker-entrypoint-initdb.d/init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass yourpassword

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
    volumes:
      - ./scraper:/app

  traffic-generator:
    build: ./traffic-generator
    container_name: traffic-generator
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "yourpassword"
    volumes:
      - ./traffic-generator:/app

volumes:
  mongodb_data:
  redis_data:
